# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cas_lineadapt <- function(df, sep_len) {
    .Call(`_telemac_cas_lineadapt`, df, sep_len)
}

find_ikle <- function(T, P) {
    .Call(`_telemac_find_ikle`, T, P)
}

find_ipobo <- function(ikle, x, y) {
    .Call(`_telemac_find_ipobo`, ikle, x, y)
}

get_edges <- function(ikle) {
    .Call(`_telemac_get_edges`, ikle)
}

interpol_grd <- function(x, y, z, ikle, xgrd, ygrd, grd) {
    .Call(`_telemac_interpol_grd`, x, y, z, ikle, xgrd, ygrd, grd)
}

line_seg_adapt <- function(x, y, s) {
    .Call(`_telemac_line_seg_adapt`, x, y, s)
}

